apiVersion: v1
kind: Secret
metadata:
  name: k8syncer-config
  namespace: {{ .Release.Namespace }}
  labels:
    chart-name: "{{ .Chart.Name }}"
    chart-version: "{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
stringData:
  config.yaml: |
    syncConfigs:
{{ .Values.config.syncConfigs | toYaml | indent 4 }}
    storageDefinitions:
{{ .Values.config.storageDefinitions | toYaml | indent 4 }}
